/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=conversation-store/wrangler.jsonc --include-runtime=false conversation-store/worker-configuration.d.ts` (hash: b58ee355842ae8d16936e4c2bf566b11)
interface __BaseEnv_Env {
	ANSWER_CACHE: KVNamespace;
	DB: D1Database;
	RETENTION_DAYS: "90";
	INGEST_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RETENTION_DAYS" | "INGEST_SECRET">> {}
}
